export interface Term {
  term: string
  def: string
  lesson?: string
}

export const GLOSSARY: Term[] = [
  { term: 'Packet', def: 'A small chunk of data with a header saying where it came from and where it is going. Messages are split into packets.', lesson: 'what-is-a-network' },
  { term: 'Packet switching', def: 'Sharing links between everyone by sending independent packets, instead of reserving a path per conversation.', lesson: 'what-is-a-network' },
  { term: 'Latency', def: 'How long data takes to get from A to B. Usually measured as round‑trip time (RTT).', lesson: 'latency-bandwidth' },
  { term: 'Bandwidth', def: 'The maximum rate a link can carry, in bits per second.', lesson: 'latency-bandwidth' },
  { term: 'Throughput', def: 'The rate you actually achieve. Always ≤ bandwidth.', lesson: 'latency-bandwidth' },
  { term: 'RTT', def: 'Round‑trip time: there and back again. Most protocols pay it at least once per exchange.', lesson: 'latency-bandwidth' },
  { term: 'p99', def: '99th percentile latency: 99 of 100 requests are faster than this. It captures the slow tail that averages hide.' },
  { term: 'Goodput', def: 'Useful, successful work delivered per second, excluding retries, errors and junk.' },
  { term: 'OSI model', def: 'A 7‑layer reference model. In practice people refer to L2 (link), L3 (network), L4 (transport) and L7 (application).', lesson: 'layers' },
  { term: 'Encapsulation', def: 'Wrapping data from a higher layer inside a header for a lower layer, like envelopes inside envelopes.', lesson: 'layers' },
  { term: 'MAC address', def: 'A 48‑bit hardware address on a network card, used for delivery within one local network.', lesson: 'switching' },
  { term: 'Switch', def: 'A Layer 2 device that forwards Ethernet frames by MAC address and learns where each address lives.', lesson: 'switching' },
  { term: 'Broadcast', def: 'A frame sent to everyone on the local network (ff:ff:ff:ff:ff:ff).', lesson: 'arp' },
  { term: 'ARP', def: 'Address Resolution Protocol: finds the MAC address that belongs to an IP address on the local network.', lesson: 'arp' },
  { term: 'DHCP', def: 'Hands out IP address, mask, gateway and DNS to devices that join a network (Discover, Offer, Request, Ack).', lesson: 'dhcp' },
  { term: 'VLAN', def: 'A virtual LAN: one physical switch split into separate broadcast domains using 802.1Q tags.', lesson: 'vlans' },
  { term: 'MTU', def: 'Maximum transmission unit: the largest packet a link carries without fragmenting, typically 1,500 bytes on Ethernet.', lesson: 'vpn' },
  { term: 'IP address', def: 'A Layer 3 address that identifies a host across networks. IPv4 is 32 bits; IPv6 is 128 bits.', lesson: 'ip-subnets' },
  { term: 'Subnet / CIDR', def: 'A range of addresses written as prefix/length, e.g. 192.168.1.0/24. The length says how many leading bits are the network.', lesson: 'ip-subnets' },
  { term: 'Default gateway', def: 'The router a host sends packets to when the destination is not on its own subnet.', lesson: 'ip-subnets' },
  { term: 'Router', def: 'A Layer 3 device that forwards packets between networks using a routing table.', lesson: 'routing' },
  { term: 'Longest‑prefix match', def: 'When several routes match, the one with the longest (most specific) prefix wins.', lesson: 'routing' },
  { term: 'TTL', def: 'Time to live: decremented by every router; the packet is dropped at zero. Prevents infinite loops.', lesson: 'routing' },
  { term: 'NAT', def: 'Network Address Translation: rewrites private addresses/ports to a public one so many devices share it.', lesson: 'nat' },
  { term: 'ICMP', def: 'IP’s control messages: echo (ping), time exceeded (traceroute), destination unreachable.', lesson: 'traceroute' },
  { term: 'BGP', def: 'Border Gateway Protocol: how autonomous systems announce which IP prefixes they can reach.', lesson: 'bgp' },
  { term: 'Autonomous system (AS)', def: 'A network under one administrative control with its own routing policy and AS number.', lesson: 'bgp' },
  { term: 'Anycast', def: 'Announcing the same IP from many locations so each user reaches the nearest one. Used by CDNs and DNS.', lesson: 'cdn' },
  { term: 'Port', def: 'A 16‑bit number identifying an application on a host (443 = HTTPS, 22 = SSH, 53 = DNS).', lesson: 'ports-udp-tcp' },
  { term: 'UDP', def: 'A minimal transport: ports plus a checksum. No connection, no reliability, no ordering.', lesson: 'ports-udp-tcp' },
  { term: 'TCP', def: 'A reliable, ordered byte‑stream transport with handshakes, ACKs, retransmission, flow and congestion control.', lesson: 'tcp-handshake' },
  { term: 'Three‑way handshake', def: 'SYN, SYN‑ACK, ACK: how TCP opens a connection and agrees on sequence numbers.', lesson: 'tcp-handshake' },
  { term: 'Retransmission timeout (RTO)', def: 'How long TCP waits before resending unacknowledged data. At least 200 ms on Linux.', lesson: 'tcp-reliability' },
  { term: 'Head‑of‑line blocking', def: 'When one lost or slow item holds up everything queued behind it.', lesson: 'tcp-reliability' },
  { term: 'Bandwidth‑delay product', def: 'Bandwidth × RTT: how much data must be in flight to keep a link full.', lesson: 'flow-control' },
  { term: 'Congestion window (cwnd)', def: 'TCP’s self‑imposed limit on data in flight, grown and shrunk to probe for capacity.', lesson: 'congestion' },
  { term: 'Bufferbloat', def: 'Excessively large buffers that fill up and add huge queueing delay without dropping packets.', lesson: 'congestion' },
  { term: 'QUIC', def: 'A UDP‑based transport with built‑in TLS, independent streams and connection migration. Carries HTTP/3.', lesson: 'quic' },
  { term: 'DNS', def: 'The system that maps names (example.com) to IP addresses, via resolvers and authoritative servers.', lesson: 'dns' },
  { term: 'TTL (DNS)', def: 'How long a DNS answer may be cached.', lesson: 'dns' },
  { term: 'HTTP', def: 'The request/response protocol of the web: methods, paths, headers, status codes.', lesson: 'http' },
  { term: 'TLS', def: 'Transport Layer Security: encrypts and authenticates connections (the S in HTTPS).', lesson: 'tls' },
  { term: 'Certificate', def: 'A signed statement binding a public key to a name, issued by a certificate authority.', lesson: 'tls' },
  { term: 'SSE', def: 'Server‑Sent Events: a long‑lived HTTP response the server writes events into. Used to stream LLM tokens.', lesson: 'realtime' },
  { term: 'WebSocket', def: 'A full‑duplex message channel created by upgrading an HTTP connection.', lesson: 'realtime' },
  { term: 'CDN', def: 'Content delivery network: caches content at edge locations near users.', lesson: 'cdn' },
  { term: 'Load balancer', def: 'Spreads traffic across backends and removes unhealthy ones. L4 works on connections, L7 on HTTP requests.', lesson: 'load-balancing' },
  { term: 'Firewall', def: 'Enforces allow/deny rules on traffic. Stateful firewalls track connections.', lesson: 'firewalls' },
  { term: 'DDoS', def: 'Distributed denial of service: overwhelming a target with traffic from many sources.', lesson: 'firewalls' },
  { term: 'VPN / tunnel', def: 'Encapsulating packets inside other packets, usually encrypted, to join distant networks.', lesson: 'vpn' },
  { term: 'Leaf‑spine (Clos)', def: 'Data‑centre topology where every leaf switch connects to every spine; any‑to‑any is two hops.', lesson: 'datacenter' },
  { term: 'ECMP', def: 'Equal‑cost multi‑path: hashing flows across several equally good paths.', lesson: 'datacenter' },
  { term: 'Oversubscription', def: 'Ratio of downstream to upstream capacity on a switch. 1:1 means non‑blocking.', lesson: 'datacenter' },
  { term: 'NVLink', def: 'NVIDIA’s high‑bandwidth GPU‑to‑GPU interconnect inside a server or rack (scale‑up).', lesson: 'gpu-interconnects' },
  { term: 'InfiniBand', def: 'A lossless, low‑latency network fabric with native RDMA, common in AI clusters (scale‑out).', lesson: 'gpu-interconnects' },
  { term: 'RoCE', def: 'RDMA over Converged Ethernet: RDMA carried in UDP/IP on Ethernet.', lesson: 'rdma' },
  { term: 'RDMA', def: 'Remote direct memory access: NICs read/write remote memory without involving the CPU or kernel.', lesson: 'rdma' },
  { term: 'All‑reduce', def: 'A collective where every participant ends up with the sum of everyone’s data. Used for gradients.', lesson: 'allreduce' },
  { term: 'NCCL', def: 'NVIDIA’s collective communications library (all‑reduce, all‑gather, all‑to‑all…).', lesson: 'allreduce' },
  { term: 'Tensor / pipeline / data parallelism', def: 'Ways of splitting model training across GPUs: within layers, across layers, or across data.', lesson: 'parallelism' },
  { term: 'Incast', def: 'Many senders transmitting to one receiver at once, overflowing the switch port buffer.', lesson: 'incast' },
  { term: 'ECN', def: 'Explicit Congestion Notification: switches mark packets instead of dropping them so senders slow down.', lesson: 'incast' },
  { term: 'PFC', def: 'Priority Flow Control: Ethernet PAUSE frames per traffic class, used to make RoCE lossless.', lesson: 'incast' },
  { term: 'KV cache', def: 'Stored attention keys/values for tokens already processed, so an LLM need not recompute them.', lesson: 'inference' },
  { term: 'TTFT / TPOT', def: 'Time to first token and time per output token: the two latency numbers for LLM serving.', lesson: 'inference' },
  { term: 'Continuous batching', def: 'Adding and removing requests from a running GPU batch each step to keep utilisation high.', lesson: 'inference' },
  { term: 'Utilisation', def: 'Arrival rate ÷ capacity. Waiting time rises sharply as it approaches 100%.' },
  { term: 'Queue', def: 'Work waiting its turn. Queues absorb bursts but convert overload into latency.' },
]
